title: "Books 'n Papers"
handle: "@booksnpapers"
url: https://booksnpapers.de/
description: "Auf **@booksnpapers** be­sprechen wir jeden Monat gemeinsam ein Buch bzw. ein wissenschaftliches Paper zum Thema Journalismus. Im Idealfall begleiten die Autor:innen die jeweilige Dis­kus­sion."