title: "Books 'n Papers"
description: "Auf Books 'n Papers be­sprechen wir jeden Monat gemeinsam ein Buch bzw. ein wissenschaftliches Paper zum Thema Journalismus. Im Idealfall begleiten die Autor:innen die jeweilige Dis­kus­sion."
url: "https://booksnpapers.de"
author:
  twitter: "@soerenengels"
twitter:
  username: "@booksnpapers"
  card: summary

social:
  name: "Books n' Papers"
  links:
    - "https://twitter.com/booksnpapers"
    - "https://github.com/soerenengels/booksnpapers"
lang: de_DE
seo:
  type: "Organization"
  logo: "/assets/logo-social.png"
  name: "@booksnpapers"
  description: "digitaler Journalismus-Buchclub"

handle: "@booksnpapers"
exclude: ["README.md"]
future: true

plugins:
  - jekyll-last-modified-at
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
